---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}

library(flexdashboard)
library(shiny)
library(tidyverse)
library(tidytext)
library(textdata)
library(rvest)
library(wordcloud)

```

```{r}
# list of books 
books <- c("1 Nephi", "2 Nephi", "Jacob", "Enos", "Jarom", "Omni", "Words of Mormon", "Mosiah", "Alma", "Helaman", "3 Nephi", "4 Nephi", "Mormon", "Ether", "Moroni")

booklist <- tibble(books) %>% 
  mutate(
    num_chapters = as.vector(c(22, 33, 7, 1, 1, 1, 1, 29, 63, 16, 30, 1, 9, 15, 10)),
    book_code = as.character(c("1-ne", "2-ne", "jacob", "enos", "jarom", "omni", "w-of-m", "mosiah", "alma", "hel", "3-ne", "4-ne", "morm", "ether", "moro"))
  )

```

```{r preprocessing}

# Loop thru book_codes and chapters to scrape data

# practice using the book codes
for (j in seq(booklist$book_code)) {
  code <- booklist$book_code[j]
  x <- paste0("this is the book code", code)
  print(x)
}

# practice using chapters
for (j in seq(booklist$num_chapters)) {
  chapter <- booklist$num_chapters[j]
  x <- paste0("this is book has ", chapter, " chapter(s)")
  print(x)
  print(1:chapter)
}

for (i in seq(chapter)) {
  print(i)
}

for (i in seq(booklist$book_code)) {
  # get book code
  code <- booklist$book_code[i]
  # filter by book code
  x <- booklist %>% filter(book_code == code)
  
  for (j in seq(x$num_chapters)) {
    # get chapters
    chapters <- x$num_chapters[j]
    # Web scrap
    text <- read_html(paste0("https://www.churchofjesuschrist.org/study/scriptures/bofm/", code, "/", j, "?lang=eng")) %>%
      html_nodes("#content") %>% # the part of the website you want, Selector Gadget to find out the node
      html_text() %>% 
      str_split("(\\.|\\:)(\\d|\\d\\d)\\s") %>%
      unlist()
    # Tidy Text
    y <- tibble(text) %>% 
      mutate(
        verse = row_number(),
        chapter = j
      ) %>% 
      unnest_tokens(word, text) %>% 
      anti_join(stop_words)
    # if first iteration
    if(j == 1 & code == "1-ne") {
      tidy_text <- y
    }
    # Combine the tibbles
    tidy_text <- rbind(tidy_text, y)
  }

}


# get vector of chapters in 1 Nephi
chapters <- as.vector(1:22)

# Web Scrapping
for (i in chapters) {
  # Web scrap
  text <- read_html(paste0("https://www.churchofjesuschrist.org/study/scriptures/bofm/1-ne/", i, "?lang=eng")) %>%
    html_nodes("#content") %>% # the part of the website you want, Selector Gadget to find out the node name
    html_text() %>% 
    str_split("(\\.|\\:)(\\d|\\d\\d)\\s") %>%
    unlist()
  # Tidy Text
  x <- tibble(text) %>% 
    mutate(
      verse = row_number(),
      chapter = i
    ) %>% 
    unnest_tokens(word, text) %>% 
    anti_join(stop_words)
  # if first iteration
  if(i == 1) {
    tidy_text <- x
  }
  # Combine the tibbles
  tidy_text <- rbind(tidy_text, x)
}

```

Sidebar {.sidebar}
-----------------------------------------------------------------------

```{r}

selectInput(
  "book",
  label = "Select Book",
  choices = books,
  selected = "1 Nephi"
)

selectInput(
  "chp",
  label = "Select Chapter",
  choices = c(chapters, "all"),
  selected = "all"
)


```


Column {data-width=650}
-----------------------------------------------------------------------

### Top Words Used

```{r}
tidy_text %>%
  filter(chapter == 1) %>% 
  count(word) %>%
  mutate(word = fct_reorder(word, n)) %>%
  filter(n > 8) %>%
  ggplot(aes(x = word, y = n)) +
  geom_col() + 
  coord_flip()
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
tidy_text %>% 
  filter(chapter == 1) %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(verse, sentiment) %>% 
  pivot_wider(
    names_from = sentiment,
    values_from = n,
    values_fill = list(n = 0)
  ) %>% 
  mutate(sentiment = positive - negative) %>% 
  ggplot(aes(verse, sentiment)) +
  geom_col()

```

### Word Cloud

```{r}

# Make a word cloud as well for another visualization practice
set.seed(42)

# the colors help show the more important words over the not as important ones
tidy_excited %>% 
  count(word) %>% 
  with(wordcloud(
  word, n, min.freq = 1, random.order=FALSE, rot.per=0.35, 
  colors=brewer.pal(8, "Dark2")
))

```

